### ISSUE TITLE
Starting Tile missplaced

### ISSUE THREAD

**Issue by Niduin** [dymanoid/MoreVehicles#6] opened 2020-03-28 13:05 UTC
i have a weird issue with this mod. If enabled and starting a new game the starting tile is misplaced (not in the center of the map). If i disable the mod the starting tile is set correctly in the centre of the map !?

Kann es zur Not gerne auch auf Deutsch erklären, falls es nicht verständlich war :-)

**Comment by dymanoid** [comment] 2020-03-28 13:47
This issue cannot be caused by More Vehicles by itself. This mod only affects vehicles but nothing more. It might be caused by a different mod that goes mad because of incompatibility with More Vehicles.

Please provide:
- a screenshot showing the issue
- the log file
- the list of active mods

**Comment by Niduin** [comment] 2020-03-28 13:54
I try to find the incompatible mod by disabling one by one. ill give you then the info.

**Comment by Niduin** [comment] 2020-03-28 14:17
Ok i found the incompatible Mod. It is the Metro Overhaul Mod. 
When MOM is enable the issue appears.

**Comment by dymanoid** [comment] 2020-03-28 14:29
Closing as duplicate of #2.

**Closed as completed by dymanoid** 2020-03-28 14:29 UTC
